openapi: 3.1.0
info:
  version: 1.0.0
  title: Product Store
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    Product Store
tags:
  - name: Products
    description: Operations with products.
servers:
  - url: http://localhost:3000
paths:
  /products:
    get:
      $ref: '../swagger/path/products/get.yaml'
    post:
      $ref: '../swagger/path/products/post.yaml'
  /products/{productId}:
    get:
      $ref: '../swagger/path/products/{id}/get.yaml'
    patch:
      $ref: '../swagger/path/products/{id}/patch.yaml'
    delete:
      $ref: '../swagger/path/products/{id}/delete.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
