type: object
required:
  - _id
  - name
  - price
  - category
  - userId
properties:
  _id:
    description: "Product's id"
    type: string
    example: 65e4decdd286b30065d54af9
  name:
    description: "Product's name"
    type: string
    example: 'apple'
  price:
    description: "Product's price"
    type: number
    example: 12
  category:
    description: "Product's category"
    type: string
    enum: ['books', 'electronics', 'clothing', 'other']
  userId:
    description: "User's id"
    type: string
    example: 65e4decdd286b30065d54af9
  description:
    description: 'Description of product'
    type: string
    example: 'best product'
  createdAt:
    description: 'Created product date&time'
    type: string
    format: date-time
    example: '2025-03-21T20:47:45.791Z'
  updatedAt:
    description: 'Updated product date&time'
    type: string
    format: date-time
    example: '2025-03-21T20:47:45.791Z'
